# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(482, 472)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.time_country = QtWidgets.QPushButton(self.centralwidget)
        self.time_country.setGeometry(QtCore.QRect(0, 400, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.time_country.setFont(font)
        self.time_country.setObjectName("time_country")
        self.timer = QtWidgets.QPushButton(self.centralwidget)
        self.timer.setGeometry(QtCore.QRect(160, 400, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.timer.setFont(font)
        self.timer.setObjectName("timer")
        self.second_time = QtWidgets.QPushButton(self.centralwidget)
        self.second_time.setGeometry(QtCore.QRect(320, 400, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.second_time.setFont(font)
        self.second_time.setObjectName("second_time")
        self.number = QtWidgets.QLabel(self.centralwidget)
        self.number.setGeometry(QtCore.QRect(70, 30, 341, 201))
        self.number.setStyleSheet("border: 5px solid;\n"
"border-radius: 25px;\n"
"font-size: 70px;\n"
"text-align: center;")
        self.number.setAlignment(QtCore.Qt.AlignCenter)
        self.number.setObjectName("number")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.time_country.setText(_translate("MainWindow", "World Time"))
        self.timer.setText(_translate("MainWindow", "Timer"))
        self.second_time.setText(_translate("MainWindow","Stopwatch"))
        self.number.setText(_translate("MainWindow", "19:46"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
